### ISSUE TITLE
App · ⚠️  Extension(@quasar/qwindow): is not compatible with quasar v2.0.0-beta.7. Required version: ^1.5.0

### ISSUE THREAD

**Issue by botura** [hawkeye64/app-extension-qwindow#22]
Any plan to upgrade this extension to Quasar v2?

**Comment by hawkeye64** [comment]
Yes, when Quasar v2 is released and has support for Vue 3 app-extensions

**Comment by piovezanfernando** [comment]
Hello, are there any plans to update this plugin to Quasar V2 or will it be discontinued? I ask because I am going to start a project and intended to use this plugin, but if it is discontinued I will change the usage strategy.

Thank you

**Comment by hawkeye64** [comment]
@fernandopiovezan1 I would like to deprecate it. This one is a pain to maintain and needs lots of work.
