### ISSUE TITLE
Maximize/minimize window reset dynamic content 

### ISSUE THREAD

**Issue by snakems** [hawkeye64/app-extension-qwindow#23]
QWindow DOM-structure reseted to default after maximize/minimize window.

Example bug:
https://codepen.io/snakems/pen/QWdoWNw

**Comment by hawkeye64** [comment]
@snakems Can you provide a better explanation of what the issue is? I'm not seeing it.

**Comment by snakems** [comment]
@hawkeye64 
If change content in window, then maximize it, changes is gone
![2021-04-26_17-28-05](https://user-images.githubusercontent.com/3106717/116099870-11089a80-a6b5-11eb-9761-a61be39c85dc.gif)

**Comment by hawkeye64** [comment]
@snakems That's because you are setting the innerHTML and when Vue redraws, it's not in the Virtual DOM, so gets overwritten (or, in this case, not written at all). Here is an updated codepen doing it the Vue way: https://codepen.io/Hawkeye64/pen/yLgwMrx?editors=1010
